### ISSUE TITLE
(floor n) should be (ceiling n)

### ISSUE THREAD

**Issue by dwayne** [sicp-lang/sicp#11]
```scheme
(define (ceiling->exact n)
  (inexact->exact (floor n)))
```

See https://github.com/sicp-lang/sicp/blob/62e7e0dd26967adda89373454c92c59908886ca0/sicp-pict/mit-support.scm#L16.

**Comment by sorawee** [comment]
Thank you! It's indeed wrong, but we switched to a new implementation of `sicp-pict` recently, so the bug is a dead code right now. I will delete the file soon, so there's no need to fix it.
