### ISSUE TITLE
Some machine time related procedures are not provided yet

### ISSUE THREAD

**Issue by muzimuzhi** [sicp-lang/sicp#15]
Some procedures under topic "machine time", like `process-time-clock` and `with-timings`, are not provided yet, while they are listed in the [MIT/GNU Scheme docs](https://www.gnu.org/software/mit-scheme/documentation/mit-scheme-ref/Machine-Time.html#Machine-Time). And this fact is verified with mit-scheme, installed by `brew install scheme` under macOS. 

I came across this issue in this [blog](https://logicgrimoire.wordpress.com/2013/01/27/attempting-to-count-change-iteratively/), in which the author defines a procedure on top of `with-timings` to print the run/gc/actual time of a procedure.

**Comment by soegaard** [comment]
Where in the book are these procedures mentioned?

**Comment by muzimuzhi** [comment]
I'm afraid they are not mentioned in the book, as I just finished chap. 1.

Maybe I have got a wrong judgement when I opened this issue, that this package aims to provide a re-implementation of the whole mit-scheme, not just a learning help to allow students finish the wizard book with DrRacket.

sorry
